apiVersion: apps/v1
kind: Deployment

metadata:
  name: testwbapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: testwbapp

  template:
    metadata:
      labels:
        app: testwbapp

    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      containers:
        - name: testwbapp
          image: YOUR_DOCKERHUB_USERNAME/testwbapp:${IMAGE_TAG}
          imagePullPolicy: Always

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"



apiVersion: v1
kind: Service

metadata:
  name: testwbapp

spec:
  selector:
    app: testwbapp

  type: ClusterIP

  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000